[package]
name = "example_resource"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alt = { path = "../altvx", package = "altvx" }
cxx = "1.0.91"

[lib]
crate-type = ["cdylib"]
